### ISSUE TITLE
KeyError: 'key'

### ISSUE THREAD

**Issue by vadeex** [backslash/hCaptcha-Solver-2.0#2]
Hey,

is this still working? I am getting an key error on the ``https://hcaptcha.com/getcaptcha`` step.

**Comment by landaida** [comment]
Same error as @vadeex  for me

![image](https://user-images.githubusercontent.com/5694096/106674981-f67dc400-6592-11eb-96c6-1b3fe8b65d8e.png)

**Comment by VXsz** [comment]
does anyone have an idea why it's refusing the requests?

relevant: https://github.com/JimmyLaurent/hcaptcha-solver/issues/13, pretty informative but I couldn't grasp half of it, specially since I don't know JS

I tried a simple adding `'v':'e0a51cf',` to the json post request but it still doesn't work, seems like something of a bigger issue

**Comment by aw1875** [comment]
> does anyone have an idea why it's refusing the requests?
> 
> relevant: [JimmyLaurent/hcaptcha-solver#13](https://github.com/JimmyLaurent/hcaptcha-solver/issues/13), pretty informative but I couldn't grasp half of it, specially since I don't know JS
> 
> I tried a simple adding `'v':'e0a51cf',` to the json post request but it still doesn't work, seems like something of a bigger issue

What is the error you're receiving from the response? There are a few different work arounds I have found as I had been working on automating hCaptcha requests using puppeteer I got a fairly in depth look and I may be able to help.

**Comment by VXsz** [comment]
I can't actually believe this, I think **fixed** it

Looks like the result.js file just needed to be updated, I basically took a new hsw.js (that you get it from hCaptcha's tons of requests) and pasted it over the old results.js (after the first few lines of code)

I was literally just playing around since I lost hope, and never thought it would be JS file, rather I thought it was the request had wrong data sent or something of sort

I'm still not sure if you only need one updated JS or different ones for each website, but it worked for now on the democaptcha.com site, but not on discord for some reason, discord says `response-already-used-error` not sure why

btw @aw1875 the responses I got either had `invalid-data` or had nothing in the brackets that explain why it the request wasn't successful and looked like this `[]` when I was playing with the post request data

**Comment by VXsz** [comment]
Made a pull request, thanks for info, I can finally relax

**Comment by zhukovleonid121** [comment]
> I can't actually believe this, I think **fixed** it
> 
> Looks like the result.js file just needed to be updated, I basically took a new hsw.js (that you get it from hCaptcha) and pasted it over the old results.js (after the first few lines of code)
> 
> I was literally just playing around since I lost hope, and never thought it would be the JS file, rather I thought it was the request had wrong data sent or something of sort
> 
> I'm still not sure if you only need one updated JS or different ones for each website, but it worked for now on the democaptcha.com site
> 
> ~but not on discord for some reason, discord says `response-already-used-error` not sure why~, Fixed, it was an issue on my side (I'm an idiot)
> 
> Yay it's fully working, I'll make a pull request soon
> 
> btw @aw1875 the responses I got either had `invalid-data` or had nothing in the brackets that explain why it the request wasn't successful and looked like this `[]` when I was playing with the post request data

Thank! it worked for me too. I also had to update chromedriver, then everything worked as it should. Have you ever thought about making something like a web panel that will stand on a powerful server and accept hcaptcha requests? The software sends a request for the solution of one hcaptcha with the desired sitekey and waits for a response from the server, then receiving a response, it already uses it for its intended purpose. You can configure a proxy for hcaptcha locally on a powerful server and receive requests from the software without loading the main computer. On the server, make a multithreaded hcaptcha solution so that it is busy only with this, and on the main PC, use the requests as intended. Such powerful PCs can be rented from Azur or somewhere else where they give a trial, I think it's convenient.

**Comment by MatheusVp2** [comment]
What was the solution to this problem?

![image](https://user-images.githubusercontent.com/12617396/112912817-db30c000-90ce-11eb-85b3-ee2c10871290.png)
